@URL=https://nwtw317ise.execute-api.eu-north-1.amazonaws.com/prod/


POST {{URL}} HTTP/1.1
Content-Type: application/json

{
    "sourceLang": "en",
    "targetLang": "bn",
    "sourceText": "Hello, how are you?"
}

###

GET {{URL}} HTTP/1.1
